# Generated by Django 2.2.13 on 2021-02-24 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('filas', models.IntegerField()),
                ('asientos', models.IntegerField()),
                ('precio_base', models.FloatField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula_id', models.ImageField(upload_to='')),
                ('precio', models.FloatField(default=0)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activa', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funciones', to='api.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('numero_asiento', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(1, 'Disponible'), (5, 'No disponible')], default=1)),
                ('funcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='butacas', to='api.Funcion')),
            ],
        ),
    ]
