# Generated by Django 2.2.13 on 2021-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_butaca_funcion_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='pelicula_id',
            field=models.IntegerField(),
        ),
    ]
