# Generated by Django 2.2.13 on 2021-02-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='asientos_fila',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
