# Generated by Django 2.2.13 on 2021-02-25 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210224_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='funcion',
            name='fecha_hora_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcion',
            name='fecha_hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
