# Generated by Django 2.2.13 on 2021-02-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210225_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='fecha',
        ),
    ]
