# Generated by Django 2.2.13 on 2021-02-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_funcion_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
