# Generated by Django 2.2.13 on 2021-02-28 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butaca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_comprados', to='api.Butaca')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos', to='api.Compra')),
            ],
        ),
    ]
