# Generated by Django 2.2.13 on 2021-03-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_compra_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='comida')),
                ('precio', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoletoComida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='api.Comida')),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_comida', to='api.Compra')),
            ],
        ),
    ]
