# Generated by Django 2.2.13 on 2021-03-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_boletocomida_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletocomida',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_boletos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_comida',
            field=models.FloatField(default=0),
        ),
    ]
